### ISSUE TITLE
Crashes upon clicking on Anvil

### ISSUE THREAD

**Issue by the-n1n** [HiWord9/RPRenames-fabric#21]
Minecraft Crashes upon clicking on an anvil. It produces this error when crashing:
```
Mixin` apply for mod rprenames failed rprenames.mixins.json:AnvilScreenMixin from mod rprenames -> net.minecraft.class_471: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unsupported JUMP opcode in initialiser in rprenames.mixins.json:AnvilScreenMixin from mod rprenames [ -> MAIN Applicator Phase -> rprenames.mixins.json:AnvilScreenMixin from mod rprenames -> Apply Initialisers]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unsupported JUMP opcode in initialiser in rprenames.mixins.json:AnvilScreenMixin from mod rprenames [ -> MAIN Applicator Phase -> rprenames.mixins.json:AnvilScreenMixin from mod rprenames -> Apply Initialisers]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.injectInitialiser(MixinApplicatorStandard.java:969)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInitialisers(MixinApplicatorStandard.java:797)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3929.<clinit>(class_3929.java:90)
	at net.minecraft.class_634.method_17587(class_634.java:1063)
	at net.minecraft.class_3944.method_17591(class_3944.java:37)
	at net.minecraft.class_3944.method_11054(class_3944.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1129)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
04:23:41.146
net.minecraft.class_310
Render thread
Unreported exception thrown!
java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_471 failed
	at net.minecraft.class_3929.<clinit>(class_3929.java:90)
	at net.minecraft.class_634.method_17587(class_634.java:1063)
	at net.minecraft.class_3944.method_17591(class_3944.java:37)
	at net.minecraft.class_3944.method_11054(class_3944.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1129)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_471 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [rprenames.mixins.json:AnvilScreenMixin from mod rprenames] from phase [DEFAULT] in config [rprenames.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 24 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unsupported JUMP opcode in initialiser in rprenames.mixins.json:AnvilScreenMixin from mod rprenames [ -> MAIN Applicator Phase -> rprenames.mixins.json:AnvilScreenMixin from mod rprenames -> Apply Initialisers]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.injectInitialiser(MixinApplicatorStandard.java:969)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInitialisers(MixinApplicatorStandard.java:797)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more
	```

**Comment by HiWord9** [comment]
Tell me please the game's version and i need ur mod's list or crash-report file for this crash

**Comment by HiWord9** [comment]
After a few tests i think that this problem is depended by some mods u have, i should test it with ur mods list to find out

**Comment by the-n1n** [comment]
[crash-2023-05-18_04.23.42-client.txt](https://github.com/HiWord9/RPRenames-fabric/files/11510902/crash-2023-05-18_04.23.42-client.txt)
I believe this is the correct crash report. The version is 1.19.2 with the latest version of the mod.

**Comment by HiWord9** [comment]
Try to update ur fabric-loader to the latest version and let me know if it helped.
I've simulated this bug and found that my minecraft can't run on quilt-loader 0.17.11 but works fine with same mods on quilt-loader 0.19.1 and fabric-loader 0.14.18. Hope that is the issue and nothing more
